// Country flag and data utilities
export const countryFlags: Record<string, string> = {
  'Portugal': '🇵🇹',
  'Japan': '🇯🇵',
  'United States': '🇺🇸',
  'France': '🇫🇷',
  'Italy': '🇮🇹',
  'Spain': '🇪🇸',
  'Germany': '🇩🇪',
  'United Kingdom': '🇬🇧',
  'Australia': '🇦🇺',
  'Brazil': '🇧🇷',
  'Canada': '🇨🇦',
  'Mexico': '🇲🇽',
  'Thailand': '🇹🇭',
  'Vietnam': '🇻🇳',
  'Indonesia': '🇮🇩',
  'Greece': '🇬🇷',
  'Netherlands': '🇳🇱',
  'Switzerland': '🇨🇭',
  'Austria': '🇦🇹',
  'Belgium': '🇧🇪',
  'Czech Republic': '🇨🇿',
  'Poland': '🇵🇱',
  'Turkey': '🇹🇷',
  'Egypt': '🇪🇬',
  'Morocco': '🇲🇦',
  'South Africa': '🇿🇦',
  'India': '🇮🇳',
  'China': '🇨🇳',
  'South Korea': '🇰🇷',
  'Singapore': '🇸🇬',
  'New Zealand': '🇳🇿',
  'Argentina': '🇦🇷',
  'Colombia': '🇨🇴',
  'Peru': '🇵🇪',
  'Chile': '🇨🇱',
  'Ireland': '🇮🇪',
  'Iceland': '🇮🇸',
  'Norway': '🇳🇴',
  'Sweden': '🇸🇪',
  'Denmark': '🇩🇰',
  'Finland': '🇫🇮',
  'Croatia': '🇭🇷',
  'Hungary': '🇭🇺',
  'Romania': '🇷🇴',
};

export const cityToCountry: Record<string, string> = {
  'Lisbon': 'Portugal',
  'Porto': 'Portugal',
  'Tokyo': 'Japan',
  'Osaka': 'Japan',
  'Kyoto': 'Japan',
  'New York': 'United States',
  'Los Angeles': 'United States',
  'San Francisco': 'United States',
  'Miami': 'United States',
  'Chicago': 'United States',
  'Paris': 'France',
  'Nice': 'France',
  'Lyon': 'France',
  'Rome': 'Italy',
  'Milan': 'Italy',
  'Florence': 'Italy',
  'Venice': 'Italy',
  'Barcelona': 'Spain',
  'Madrid': 'Spain',
  'Berlin': 'Germany',
  'Munich': 'Germany',
  'London': 'United Kingdom',
  'Edinburgh': 'United Kingdom',
  'Sydney': 'Australia',
  'Melbourne': 'Australia',
  'Rio de Janeiro': 'Brazil',
  'São Paulo': 'Brazil',
  'Toronto': 'Canada',
  'Vancouver': 'Canada',
  'Mexico City': 'Mexico',
  'Bangkok': 'Thailand',
  'Ho Chi Minh City': 'Vietnam',
  'Hanoi': 'Vietnam',
  'Bali': 'Indonesia',
  'Jakarta': 'Indonesia',
  'Athens': 'Greece',
  'Amsterdam': 'Netherlands',
  'Zurich': 'Switzerland',
  'Vienna': 'Austria',
  'Brussels': 'Belgium',
  'Prague': 'Czech Republic',
  'Warsaw': 'Poland',
  'Istanbul': 'Turkey',
  'Cairo': 'Egypt',
  'Marrakech': 'Morocco',
  'Cape Town': 'South Africa',
  'Mumbai': 'India',
  'Delhi': 'India',
  'Beijing': 'China',
  'Shanghai': 'China',
  'Seoul': 'South Korea',
  'Singapore': 'Singapore',
  'Auckland': 'New Zealand',
  'Buenos Aires': 'Argentina',
  'Bogotá': 'Colombia',
  'Lima': 'Peru',
  'Santiago': 'Chile',
  'Dublin': 'Ireland',
  'Reykjavik': 'Iceland',
  'Oslo': 'Norway',
  'Stockholm': 'Sweden',
  'Copenhagen': 'Denmark',
  'Helsinki': 'Finland',
  'Dubrovnik': 'Croatia',
  'Budapest': 'Hungary',
  'Bucharest': 'Romania',
};

export function getCountryFromCity(city: string): string {
  const normalizedCity = city.trim();
  return cityToCountry[normalizedCity] || 'Unknown';
}

export function getFlagForCountry(country: string): string {
  return countryFlags[country] || '🏳️';
}

export function getFlagForCountryCode(countryCode: string): string {
  const country = Object.entries(getCountryCodes()).find(([, code]) => code === countryCode)?.[0];
  return country ? getFlagForCountry(country) : '🏳️';
}

export function getCountryCode(country: string): string {
  return getCountryCodes()[country] || 'XX';
}

function getCountryCodes(): Record<string, string> {
  const codes: Record<string, string> = {
    'Portugal': 'PT',
    'Japan': 'JP',
    'United States': 'US',
    'France': 'FR',
    'Italy': 'IT',
    'Spain': 'ES',
    'Germany': 'DE',
    'United Kingdom': 'GB',
    'Australia': 'AU',
    'Brazil': 'BR',
    'Canada': 'CA',
    'Mexico': 'MX',
    'Thailand': 'TH',
    'Vietnam': 'VN',
    'Indonesia': 'ID',
    'Greece': 'GR',
    'Netherlands': 'NL',
    'Switzerland': 'CH',
    'Austria': 'AT',
    'Belgium': 'BE',
    'Czech Republic': 'CZ',
    'Poland': 'PL',
    'Turkey': 'TR',
    'Egypt': 'EG',
    'Morocco': 'MA',
    'South Africa': 'ZA',
    'India': 'IN',
    'China': 'CN',
    'South Korea': 'KR',
    'Singapore': 'SG',
    'New Zealand': 'NZ',
    'Argentina': 'AR',
    'Colombia': 'CO',
    'Peru': 'PE',
    'Chile': 'CL',
    'Ireland': 'IE',
    'Iceland': 'IS',
    'Norway': 'NO',
    'Sweden': 'SE',
    'Denmark': 'DK',
    'Finland': 'FI',
    'Croatia': 'HR',
    'Hungary': 'HU',
    'Romania': 'RO',
  };
  return codes;
}
